name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Which version you want to increment? Use MAJOR, MINOR or PATCH'
        required: true
        default: 'PATCH'
      label:
        description: 'Add Labels. i.e final, alpha, rc'
        required: false
        default: ''

jobs:
  git_release:
    name: 'Release Dry Run'
    runs-on: 'ubuntu-latest'

    steps:
      # Checkout sources
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto Semver 
        uses: "rui-costa/action-automatic-semver-releases@1.1.1"
        with:
          TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SEMVER: '${{ github.event.inputs.semver }}'
          LABEL: '${{ github.event.inputs.label }}'

  sentry_release:
    needs: git_release
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sentry Release
        uses: getsentry/action-release@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: '${{ github.event.inputs.semver }}'
          sourcemaps: "./build/assets"